{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-example.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress-example.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
  selector:
    {{- include "wordpress-example.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
{{- end }}
