{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-example.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress-example.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
type: Opaque
stringData:
  root-password: {{ .Values.mysql.rootPassword | required "mysql.rootPassword is required" | quote }}
  password: {{ .Values.mysql.password | required "mysql.password is required" | quote }}
{{- end }}
